### PR TITLE
feat: new pages updated and blog setup

### PR DESCRIPTION
**Pull request by owenmerry**
Updated alot page styles

Home page (Desktop):
screencapture-localhost-9000-2022-05-20-13_16_26

Home page (Mobile):
screencapture-localhost-9000-2022-05-20-13_16_40

Blogs:
screencapture-localhost-9000-blog-2022-05-09-22_19_08

Blog page:
screencapture-localhost-9000-blog-10-things-to-bring-on-your-first-social-ride-5-2022-05-09-22_19_30

Updated dynamic pages to bit cleaner:
screencapture-localhost-9000-rides-2022-05-09-22_19_50

### CODE REVIEW

**Review by achingbrain — CHANGES_REQUESTED** [review]
- Can you back out the logo changes please, there's some more tweaking that's needed before they are ready
- The fade from white to black everywhere is very extreme, it needs to be a bit more gentle
  - Maybe leave the footer in grey as it is
  - On the homepage I don't know, the pull-out text is nice but the background is too dark
- The "home" under the "We are a social club based out of..." on the homepage seems unnecessary and cuts the image in half - please remove
- Having the header over the image and in the body is unnecessary but I'm guessing this can be pulled out via the CMS after merge

**Comment by owenmerry** [comment]
I do disagree on the footer colour.. haven't seen that grey on anything else seems to me more off brand then on brand also with the text being white makes it hard to read the text so would be bad for accessibility.

black:
Screenshot 2022-05-25 at 22 44 47


Grey:
Screenshot 2022-05-25 at 22 42 29

**Comment by owenmerry** [comment]
I dont think just getting rid of the copy is the best decision as its meant to be where we describe the club.. i have changed some css so doesnt effect the image, and the copy isnt great right now as i just copied some existing text but i have this editable in contentful so can be perfected, but great place for introduction otherwise you will have blogs and lots other content before you get to find out what the site and club is about

Doesnt effect image now:
Screenshot 2022-05-25 at 22 46 37

**Comment by owenmerry** [comment]
"Having the header over the image and in the body is unnecessary but I'm guessing this can be pulled out via the CMS after merge"

yes all editable with contentful.. having the text on the portal utilises dead space from previous version and will help with UX when navigating.. we can pull out the double headers once its out but cant right now as these pages are live pages

**Comment by achingbrain** [comment]
> I dont think just getting rid of the copy is the best decision

Ah, sorry - that's not what I meant, what I meant was to remove the highlighted part on the home page, my apologies for the confusion:

image

> I do disagree on the footer colour.. haven't seen that grey on anything else seems to me more off brand then on brand

I don't have a massively strong opinion on what the footer colour should be... other than not black.  White might work?  A much lighter grey?  We don't have to use colours from the jersey everywhere - take a look at the Ikea website for example, if everything was their brand colours the whole thing would be blue and yellow.

> Doesnt effect image now

I think a better approach would be selecting home page images that have large amounts of empty space available and to place the intro text in the empty space; then you can eliminate the fade altogether.

**Comment by owenmerry** [comment]
`highlighted part on the home page`
If we remove the images from the homepage then this area disappears too, cant do right now as its being used on the current design.. would mean we lose the homepage slide show

` strong opinion on what the footer colour should be... other than not black.`
will remove the black and go grey

`home page images that have large amounts of empty space available`
This is also updateable from contentful so can find a image and upload it

**Comment by owenmerry** [comment]
Screenshot 2022-05-28 at 09 40 18

How about this its grey but the text and icons are still very readible

**Pull request merged**
